exec-once = waybar & mako & hypridle
layerrule = match:class waybar, blur on
layerrule = match:class rofi, blur on
exec-once = /usr/bin/pypr
exec-once = awww-daemon
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
